# Generated by Django 4.2.7 on 2023-11-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_enquiry_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
