# Generated by Django 4.2.7 on 2023-11-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_galleryimage_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='Gallery',
            new_name='gallery',
        ),
    ]
