# Generated by Django 4.2.7 on 2023-12-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_subscription_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
                ('Email_address', models.EmailField(max_length=254)),
                ('PermAddress', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('details', models.TextField()),
                ('img', models.ImageField(upload_to='Trainers/')),
            ],
        ),
    ]
