# Generated by Django 4.2.7 on 2023-12-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_trainer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='Email_address',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='FullName',
            new_name='Full_Name',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='PermAddress',
            new_name='Home_Address',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='is_active',
            new_name='Is_active',
        ),
    ]
