# Generated by Django 4.2.7 on 2023-12-19 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0025_substotrainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substotrainer',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='substotrainer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
