# Generated by Django 4.2.7 on 2023-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_substotrainer_subscriber_substotrainer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subplan',
            name='validity_period',
            field=models.IntegerField(null=True),
        ),
    ]
