# Generated by Django 4.2.7 on 2023-12-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_trainermsg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainermsg',
            name='user_type',
        ),
    ]
