# Generated by Django 4.2.7 on 2023-12-31 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0037_trainersubscriberreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainersubscriberreport',
            name='report_for_trainer',
        ),
        migrations.RemoveField(
            model_name='trainersubscriberreport',
            name='report_for_user',
        ),
        migrations.RemoveField(
            model_name='trainersubscriberreport',
            name='report_from_trainer',
        ),
        migrations.RemoveField(
            model_name='trainersubscriberreport',
            name='report_from_user',
        ),
        migrations.AddField(
            model_name='trainersubscriberreport',
            name='report_a_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_a_trainer', to='main.trainer'),
        ),
        migrations.AddField(
            model_name='trainersubscriberreport',
            name='report_a_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_a_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainersubscriberreport',
            name='reporting_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_trainer', to='main.trainer'),
        ),
        migrations.AddField(
            model_name='trainersubscriberreport',
            name='reporting_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
