# Generated by Django 4.2.7 on 2023-12-31 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_trainersubscriberreport_report_for_trainer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_logo', models.ImageField(upload_to='logo/')),
            ],
        ),
    ]
