# Generated by Django 4.2.7 on 2024-01-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_enquiry_details_alter_faq_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='img',
            new_name='profile_picture',
        ),
    ]
